[azure]
redirect_uri = "http://localhost:8501"
client_id = "0637d1eb-7633-44b3-b6c9-b101fe871fd1"
client_secret = ""
tenant_id = "95a03c20-1780-4707-aa05-9bd9b2ae18b1"

[auth_config]
expiry_days = 1
key = 'teste_ad'
name = 'teste_ad'
